server.port=8080
api.version=v1
spring.datasource.url=jdbc:postgresql://localhost:5433/yemm_db
spring.datasource.username=devdb
spring.datasource.password=a1b2c3d4
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true